# Generated by Django 3.0.2 on 2020-02-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'To do'), (1, 'In progress'), (2, 'Ready for review'), (3, 'Requires testing'), (4, 'In testing'), (5, 'Done')])),
                ('estimation', models.IntegerField(null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as', to='user.Profile')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_ini', to='user.Profile')),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_pt', to='tasks.Task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_pro', to='project.Project')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_re', to='project.Release')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sp', to='project.Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_o', to='user.Profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_t', to='tasks.Task')),
            ],
        ),
    ]
