# Generated by Django 3.0.2 on 2020-02-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200220_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Active'), (2, 'Paused'), (3, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Active'), (2, 'Paused'), (3, 'Closed')], default=0),
        ),
    ]
